name: Deploy Minified Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache npm Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install Minification Tools
        run: |
          npm install -g html-minifier terser clean-css-cli

      - name: Minify Files into Dist Directory
        run: |
          mkdir -p dist
          
          echo "Minifying HTML..."
          find . -name "*.html" -type f -exec sh -c '
            mkdir -p "dist/$(dirname "{}")" &&
            html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o "dist/{}" "{}"
          ' \;

          echo "Minifying CSS..."
          find . -name "*.css" -type f -exec sh -c '
            mkdir -p "dist/$(dirname "{}")" &&
            cleancss -o "dist/{}" "{}"
          ' \;

          echo "Minifying JavaScript..."
          find . -name "*.js" -type f -exec sh -c '
            mkdir -p "dist/$(dirname "{}")" &&
            terser --compress --mangle -o "dist/{}" -- "{}"
          ' \;

      - name: Deploy to GitHub Pages Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure pages branch exists, or create it
          if ! git ls-remote --exit-code --heads origin pages; then
            git checkout --orphan pages
          else
            git checkout pages
          fi

          # Remove old files, then copy minified files
          git rm -rf . 2>/dev/null || true  # Ignore errors if nothing to remove
          cp -r dist/* .
          rm -rf dist  # Cleanup

          touch .nojekyll  # Ensure GitHub Pages processes files properly

          if [[ -n $(git status --porcelain) ]]; then
            git add --all
            git commit -m "Deploy minified site"
            git push origin pages
          else
            echo "No changes to commit"
          fi
