name: purge-and-minify

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  checkout-minify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Install CLI tools
      - run: npm install -g terser csso-cli html-minifier

      # Use CLI tools to minify, overwriting existing files
      - run: for i in $(find . -type f -name "*.js"); do terser $i --compress -o $i; done
      - run: for i in $(find . -type f -name "*.css"); do csso $i -o $i; done
      - run: for i in $(find . -type f -name "*.html"); do html-minifier --collapse-whitespace --remove-comments $i -o $i; done
      
      # Commit changes if files were modified
      - name: Commit and Push changes
        run: |
          # Set Git config for GitHub Actions
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes and commit them
          git add .
          git diff --cached --quiet || git commit -m "Automated minify of ${{ github.sha }}"
          
          git push --force -u origin main:pages
