name: Deploy Minified Site

on:
  push:
    branches:
      - main  # Run workflow when pushing to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install -g html-minifier terser clean-css-cli

      - name: Minify HTML
        run: |
          find . -name "*.html" -type f -exec html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o {} {} \;

      - name: Minify CSS
        run: |
          find . -name "*.css" -type f -exec cleancss -o {} {} \;

      - name: Minify JavaScript
        run: |
          find . -name "*.js" -type f -exec terser --compress --mangle -o {} -- {} \;

      - name: Push to Pages Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan pages
          git rm -rf .
          git checkout main -- .
          git add .
          git commit -m "Deploy minified site"
          git push -f origin pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: .
