name: Deploy Minified Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Install Minifiers
        run: npm install -g html-minifier terser clean-css-cli

      - name: Minify Files into Dist Directory
        run: |
          mkdir -p dist
          
          # Minify HTML
          find . -name "*.html" -exec sh -c '
            mkdir -p "dist/$(dirname "{}")" &&
            html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o "dist/{}" "{}"
          ' \;

          # Minify CSS
          find . -name "*.css" -exec sh -c '
            mkdir -p "dist/$(dirname "{}")" &&
            cleancss -o "dist/{}" "{}"
          ' \;

          # Minify JavaScript
          find . -name "*.js" -exec sh -c '
            mkdir -p "dist/$(dirname "{}")" &&
            terser --compress --mangle -o "dist/{}" -- "{}"
          ' \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: pages
          keep_files: false
          force_orphan: true
