name: Deploy Minified Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          npm install -g html-minifier terser clean-css-cli

      - name: Minify Files
        run: |
          find . -name "*.html" -exec html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o {} {} \;
          find . -name "*.css" -exec cleancss -o {} {} \;
          find . -name "*.js" -exec terser --compress --mangle -o {} -- {} \;

      - name: Push to Pages Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan pages
          git reset --hard main  # Ensures files persist
          git add .
          git commit -m "Deploy minified site"
          git push -f origin pages
