name: Deploy Minified Site

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grants push access

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all branches are available

      - name: Install Dependencies
        run: |
          npm install -g html-minifier terser clean-css-cli

      - name: Minify Files into Dist Directory
        run: |
          mkdir -p dist
          
          # Minify HTML
          find . -name "*.html" -exec sh -c '
            mkdir -p "dist/$(dirname "{}")" &&
            html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o "dist/{}" "{}"
          ' \;

          # Minify CSS
          find . -name "*.css" -exec sh -c '
            mkdir -p "dist/$(dirname "{}")" &&
            cleancss -o "dist/{}" "{}"
          ' \;

          # Minify JavaScript
          find . -name "*.js" -exec sh -c '
            mkdir -p "dist/$(dirname "{}")" &&
            terser --compress --mangle -o "dist/{}" -- "{}"
          ' \;

      - name: Push Minified Files to Pages Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Switch to pages branch, or create it if missing
          git checkout pages || git checkout --orphan pages

          # Remove old files, then copy minified files
          git rm -rf .
          cp -r dist/* .

          # Ensure .nojekyll exists to allow underscore-prefixed files
          touch .nojekyll

          git add --all
          git commit -m "Deploy minified site" || echo "No changes to commit"
          git push -f origin pages
